#!/usr/bin/env python3
# DO NOT EDIT!
# This file is automatically generated.
# MAJOR and MINOR should be updated in make.py.
# BUILD and REVISION are incremented automatically.
MAJOR = 0
MINOR = 2
BUILD = 0
REVISION = 0
